-- Load Next.js snippets directly
local s = ls.snippet
local t = ls.text_node
local i = ls.insert_node
local c = ls.choice_node
local fmt = require('luasnip.extras.fmt').fmt
local rep = require('luasnip.extras').rep

-- Next.js snippets
ls.add_snippets('typescriptreact', {
  -- Next.js App Router - Page Component
  s('npage', {
    t 'export default function ',
    i(1, 'Page'),
    t '() {',
    t { '', '  return (' },
    t { '', '    <main className="flex min-h-screen flex-col items-center justify-between p-24">' },
    t { '', '      ' },
    i(2, '// Content'),
    t { '', '    </main>' },
    t { '', '  )' },
    t { '', '}' },
  }),

  -- Next.js App Router - Page with Props
  s('npagep', {
    t 'export interface ',
    i(1, 'Page'),
    t 'Props {',
    t { '', '  ' },
    i(2, '// props'),
    t { '', '}' },
    t { '', '' },
    t { '', 'export default function ' },
    rep(1),
    t '({ ',
    i(3, 'params'),
    t ' }: ',
    rep(1),
    t 'Props) {',
    t { '', '  return (' },
    t { '', '    <main className="flex min-h-screen flex-col items-center justify-between p-24">' },
    t { '', '      ' },
    i(4, '// Content'),
    t { '', '    </main>' },
    t { '', '  )' },
    t { '', '}' },
  }),

  -- Next.js API Route (App Router)
  s('napi', {
    t "import { NextRequest, NextResponse } from 'next/server'",
    t { '', '', 'export async function GET(request: NextRequest) {' },
    t { '', '  ' },
    i(1, '// Handle GET'),
    t { '', '  ', "  return NextResponse.json({ message: 'Success' })" },
    t { '', '}' },
    t { '', '', 'export async function POST(request: NextRequest) {' },
    t { '', '  const body = await request.json()', '', '  ' },
    i(2, '// Handle POST'),
    t { '', '  ', "  return NextResponse.json({ message: 'Success' })" },
    t { '', '}' },
  }),

  -- Next.js App Router - Server Component
  s('nserver', {
    t "import { Suspense } from 'react'",
    t { '', '', 'async function fetchData() {' },
    t { '', '  ' },
    i(1, '// Fetch data'),
    t { '', '  ', "  return { data: 'example' }" },
    t { '', '}' },
    t { '', '', 'export default async function ' },
    i(2, 'ServerComponent'),
    t '() {',
    t { '', '  const data = await fetchData()', '', '  return (' },
    t { '', '    <div>' },
    t { '', '      <Suspense fallback={<div>Loading...</div>}>' },
    t { '', '        ' },
    i(3, '// Content'),
    t { '', '      </Suspense>' },
    t { '', '    </div>' },
    t { '', '  )' },
    t { '', '}' },
  }),

  -- Next.js App Router - Client Component
  s('nclient', {
    t "'use client'",
    t { '', '', "import { useState } from 'react'" },
    t { '', '', 'interface ' },
    i(1, 'ClientComponent'),
    t 'Props {',
    t { '', '  ' },
    i(2, '// props'),
    t { '', '}' },
    t { '', '', 'export default function ' },
    rep(1),
    t '({ ',
    i(3, 'params'),
    t ' }: ',
    rep(1),
    t 'Props) {',
    t { '', '  const [state, setState] = useState(' },
    i(4, 'null'),
    t { ')', '', '  return (' },
    t { '', '    <div>' },
    t { '', '      ' },
    i(5, '// Content'),
    t { '', '    </div>' },
    t { '', '  )' },
    t { '', '}' },
  }),

  -- Next.js App Router - Layout Component
  s('nlayout', {
    t 'export default function ',
    i(1, 'RootLayout'),
    t '({ children }: { children: React.ReactNode }) {',
    t { '', '  return (' },
    t { '', '    <div className="flex flex-col min-h-screen">' },
    t { '', '      <header className="bg-zinc-800 text-white p-4">' },
    t { '', '        ' },
    i(2, '// Header content'),
    t { '', '      </header>' },
    t { '', '      ', '      <main className="flex-grow">' },
    t { '', '        {children}' },
    t { '', '      </main>' },
    t { '', '      ', '      <footer className="bg-zinc-800 text-white p-4">' },
    t { '', '        ' },
    i(3, '// Footer content'),
    t { '', '      </footer>' },
    t { '', '    </div>' },
    t { '', '  )' },
    t { '', '}' },
  }),

  -- Next.js App Router - Loading Component
  s('nloading', {
    t 'export default function Loading() {',
    t { '', '  return (' },
    t { '', '    <div className="flex items-center justify-center min-h-screen">' },
    t { '', '      <div className="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-gray-900"></div>' },
    t { '', '      ' },
    i(1, '// Add loading content'),
    t { '', '    </div>' },
    t { '', '  )' },
    t { '', '}' },
  }),

  -- Next.js App Router - Error Component
  s('nerror', {
    t "'use client'",
    t { '', '', "import { useEffect } from 'react'" },
    t { '', '', 'export default function Error({' },
    t { '', '  error,' },
    t { '', '  reset,' },
    t { '', '}: {' },
    t { '', '  error: Error & { digest?: string }' },
    t { '', '  reset: () => void' },
    t { '', '}) {' },
    t { '', '  useEffect(() => {' },
    t { '', '    console.error(error)' },
    t { '', '  }, [error])', '', '  return (' },
    t { '', '    <div className="flex flex-col items-center justify-center min-h-screen">' },
    t { '', '      <h2 className="text-2xl font-bold mb-4">Something went wrong!</h2>' },
    t { '', '      <button' },
    t { '', '        className="px-4 py-2 bg-blue-500 text-white rounded hover:bg-blue-600"' },
    t { '', '        onClick={() => reset()}' },
    t { '', '      >' },
    t { '', '        Try again' },
    t { '', '      </button>' },
    t { '', '      ' },
    i(1, '// Additional error UI'),
    t { '', '    </div>' },
    t { '', '  )' },
    t { '', '}' },
  }),

  -- Next.js App Router - Metadata for SEO
  s('nmeta', {
    t 'export const metadata = {',
    t { '', "  title: '" },
    i(1, 'Page Title'),
    t "',",
    t { '', "  description: '" },
    i(2, 'Page description'),
    t "',",
    t { '', '  openGraph: {' },
    t { '', "    title: '" },
    rep(1),
    t "',",
    t { '', "    description: '" },
    rep(2),
    t "',",
    t { '', "    url: '" },
    i(3, 'https://example.com'),
    t "',",
    t { '', "    siteName: '" },
    i(4, 'Site Name'),
    t "',",
    t { '', '    images: [' },
    t { '', '      {' },
    t { '', "        url: '" },
    i(5, '/images/og-image.jpg'),
    t "',",
    t { '', '        width: 1200,' },
    t { '', '        height: 630,' },
    t { '', '      },' },
    t { '', '    ],' },
    t { '', "    locale: 'en-US'," },
    t { '', "    type: 'website'," },
    t { '', '  },' },
    t { '', '}' },
  }),

  -- Next.js Server Action
  s('naction', {
    t "'use server'",
    t { '', '', 'export async function ' },
    i(1, 'serverAction'),
    t '(',
    i(2, 'data: FormData'),
    t ') {',
    t { '', '  ' },
    i(3, '// Handle the action'),
    t { '', '  ', "  return { success: true, message: 'Operation completed' }" },
    t { '', '}' },
  }),
})

return {}
